name: Tests

on:
  push:
  pull_request:

env:
  GOEXPERIMENT: rangefunc

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Test (channels)
        run: go test -v -tags channels ./...

      - name: Test (epoll)
        run: go test -v ./...
